services:
  cors-risk-website:
    build:
      context: ./website
    ports:
      - "8080:80"
    networks:
      - corsrisk-network
    depends_on:
      - risky-api

  risky-api:
    image: nginx:alpine
    volumes:
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api/data:/usr/share/nginx/html/data
    ports:
      - "8081:80"
    networks:
      - corsrisk-network

networks:
  corsrisk-network:
    driver: bridge