services:

  apisix: 
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    networks:
      - cors-network
    
  employee:
    image: nginx:alpine
    volumes:
      - ./employee-service/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./employee-service/employee:/usr/share/nginx/html/employee
    networks:
      - cors-network

  salary:
    image: nginx:alpine
    volumes:
      - ./salary-service/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./salary-service/salary:/usr/share/nginx/html/salary
    networks:
      - cors-network
  
  website:
    build:
      context: ./website
    networks:
      - cors-network
    depends_on:
      - employee
      - salary 

networks:
  cors-network:
    driver: bridge