services:
  apisix: 
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID:-default_value}
      - CLIENT_SECRET=${CLIENT_SECRET:-default_value}
      - SESSION_SECRET=${SESSION_SECRET:-default_value}
      - DISCOVERY=${DISCOVERY:-default_value}
      - REDIRECT_URI=${REDIRECT_URI:-default_value}
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    networks:
      apisix:
    
  web1:
    image: nginx:1.27.3
    restart: always
    volumes:
      - ./upstream/hello_service.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  apisix-employee: 
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID_EMPLOYEE:-default_value}
      - CLIENT_SECRET=${CLIENT_SECRET_EMPLOYEE:-default_value}
      - SESSION_SECRET=${SESSION_SECRET:-default_value}
      - DISCOVERY_EMPLOYEE=${DISCOVERY_EMPLOYEE:-default_value}
      - REDIRECT_URI_EMPLOYEE=${REDIRECT_URI_EMPLOYEE:-default_value}
    volumes:
      - ./apisix_conf/employee_config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/employee_apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9180:9080/tcp"
      - "9543:9443/tcp"
    networks:
      employee:
 
  web2:
    image: nginx:1.27.3
    restart: always
    volumes:
      - ./upstream/employee_web.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      employee:

networks:
  apisix:
    driver: bridge
  employee:
    driver: bridge
      