services:
  website:
    build:
      context: ./website
    ports:
      - "8080:80"
    networks:
      - sop-network
    depends_on:
      - api

  api:
    image: nginx:alpine
    volumes:
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api/data:/usr/share/nginx/html/data
    ports:
      - "8081:80"
    networks:
      - sop-network

networks:
  sop-network:
    driver: bridge