services:
  lighthouse:
    image: patrickhulce/lhci-server
    ports:
      - '9001:9001'
    volumes:
      - ./lhci-data:/data
    networks:
      - lhci-example
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - lhci-example
    volumes:
      - ./public:/app/public:ro

networks:
  lhci-example:
    driver: bridge