services:
  cors-sec-website:
    build:
      context: ./website
    ports:
      - "8080:80"
    networks:
      - corssec-network
    depends_on:
      - sec-api

  cors-attacker-website:
    build:
      context: ./website
    ports:
      - "8082:80"
    networks:
      - corssec-network
    depends_on:
      - sec-api
  sec-api:
    image: nginx:alpine
    volumes:
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api/data:/usr/share/nginx/html/data
    ports:
      - "8081:80"
    networks:
      - corssec-network

networks:
  corssec-network:
    driver: bridge