@startuml
actor "Developer" as dev
participant "Developer Environment" as devtools
participant "Webapp" as app
participant "Lighthouse CI" as lh

dev -> devtools : update code
group build
    devtools -> app : reload
    devtools -> lh : analyze webapp
end

lh --> dev : results from webapp analysis
dev -> app : test code changes

@enduml