@startuml
actor "Developer" as dev
participant "Development Environment" as devtools
participant "Webapp" as app
participant "Lighthouse CI" as lhci

dev -> devtools : update code
group build
    devtools -> app : reload
    devtools -> lhci : analyze webapp
end

lhci --> dev : results from webapp analysis
dev -> app : test code changes

@enduml