services:
  lighthouse:
    image: patrickhulce/lhci-server
    ports:
      - '9001:9001'
    volumes:
      - lhci-data:/data
    networks:
      - lighthouse-network
  webapp:
    image: nginx:1.27.3
    restart: always
    volumes:
      - ./webapp/webapp.conf:/etc/nginx/nginx.conf
    ports:
      - "9080:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      lighthouse-network:
volumes:
  lhci-data:
networks:
  lighthouse-network: