apisix:
  node_listen: 9080
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
  admin:
    allow_admin:
      - "0.0.0.0/0"
  
  admin_key:
    - name: "admin"
      key: "abcdefg"
      role: admin

    - name: "viewer"
      key: "abcdefg"
      role: viewer